### ISSUE TITLE
请问.yml是您自己训练的吗，还是？

### ISSUE THREAD

**Issue by ChildishChange** [ypwhs/LaughOrNot#1]
您好，我在知乎上看到您分享了您github上的项目链接。于是试着运行了一下，有一些疑问想要向您请教一下。项目文件夹里提供了几个.yml文件用来描述人的不同表情。请问这些文件是您训练得到的吗？还是在某个地方获取的？谢谢。

**Comment by ypwhs** [comment]
你可以按键盘c键直接把当前面部表情保存，从而获得这个表情的yml文件。

参考: https://github.com/ypwhs/LaughOrNot/blob/master/main.cc#L154

**Comment by ChildishChange** [comment]
谢谢！！我在您代码里有看到这一段，但是没有想到可以这么用，非常感谢！

**Comment by ChildishChange** [comment]
那这样的话，我保存下来的面部表情用来识别其他人，就不会那么准确了是吗？谢谢

**Comment by ypwhs** [comment]
是的，你可以采集更多样本，然后用使用你自己的分类器分类，比如SVM。

**Comment by ChildishChange** [comment]
您好，请问按c保存到本地的文件应该怎么使用？谢谢！
我刚刚保存了一个.yml文件，然后修改了src/ExpressionClassifier.cc第25行，添加了这个文件，编译成功之后运行失败，报了这个错
“
OpenCV Error: Assertion failed (src1.size == src2.size && src1.type() == src2.type()) in norm, file /home/change/下载/opencv-2.4.9/modules/core/src/stat.cpp, line 1978
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/change/下载/opencv-2.4.9/modules/core/src/stat.cpp:1978: error: (-215) src1.size == src2.size && src1.type() == src2.type() in function norm

已放弃 (核心已转储)
”
百度之后发现说是两者的type和size不一样。
然后我对比了一下生成的face1.yml文件和smile.yml文件，发现它们在格式上有区别。但是具体不知道要如何操作。

谢谢！

**Comment by ypwhs** [comment]
你得用objectPoints.yml，而不是 face*.yml

**Comment by ChildishChange** [comment]
。。恩，是的，我后来发现了。。谢谢！

**Comment by ChildishChange** [comment]
还有一个可能很蠢的问题。。（新手见谅。。
生成的objectPoints.yml文件里是一个198维的向量（不知道这样描述对不对），您的意思是我可以使用SVM来对更多的样本分类，然后调整得到每个表情相应的参数是吗。。。
。。我想用开源的工具来完成这个。。不知道能不能行得通。。
谢谢！
